//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.Forums = new HashSet<Forum>();
        }
    
        public int AdminID { get; set; }
        public long MemberID { get; set; }
        public string Username { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual ICollection<Forum> Forums { get; set; }
    }
}
