//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum
    {
        public Forum()
        {
            this.SubForums = new HashSet<SubForum>();
        }
    
        public int ForumID { get; set; }
        public string Title { get; set; }
        public int Admins { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual ICollection<SubForum> SubForums { get; set; }
    }
}
