//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ForumDBContext : DbContext
    {
        public ForumDBContext()
            : base("name=ForumDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
     //   public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Forum> Forums { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberType> MemberTypes { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Moderator> Moderators { get; set; }
        public virtual DbSet<SubForum> SubForums { get; set; }
        public virtual DbSet<Thread> Threads { get; set; }
    }
}
