//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Admins = new HashSet<Admin>();
            this.Moderators = new HashSet<Moderator>();
        }
    
        public long MemberID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public bool Active { get; set; }
        public int Type { get; set; }
        public int Seniority { get; set; }
    
        public virtual ICollection<Admin> Admins { get; set; }
        public virtual MemberType MemberType { get; set; }
        public virtual ICollection<Moderator> Moderators { get; set; }
    }
}
