//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long MessageID { get; set; }
        public string Topic { get; set; }
        public string Content { get; set; }
        public System.DateTime Date { get; set; }
        public long MemberID { get; set; }
        public long ThreadID { get; set; }
    
        public virtual Thread Thread { get; set; }
    }
}
