//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moderator
    {
        public Moderator()
        {
            this.SubForums = new HashSet<SubForum>();
        }
    
        public int ModeratorID { get; set; }
        public long MemberID { get; set; }
        public string Username { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual ICollection<SubForum> SubForums { get; set; }
    }
}
