//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubForum
    {
        public SubForum()
        {
            this.Threads = new HashSet<Thread>();
        }
    
        public int SubForumID { get; set; }
        public string Title { get; set; }
        public int Moderators { get; set; }
        public int ForumID { get; set; }
    
        public virtual Forum Forum { get; set; }
        public virtual Moderator Moderator { get; set; }
        public virtual ICollection<Thread> Threads { get; set; }
    }
}
