//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thread
    {
        public Thread()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public long ThreadID { get; set; }
        public string Title { get; set; }
        public int SubForumID { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
        public virtual SubForum SubForum { get; set; }
    }
}
